server {
    listen 80;
    listen [::]:80;
    server_name admin.suraksha.lk;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name admin.suraksha.lk;

    ssl_certificate     /etc/letsencrypt/live/lms.suraksha.lk/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lms.suraksha.lk/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;
    include /etc/nginx/snippets/security-headers.conf;

    root  /var/www/admin;
    index index.html;

    access_log /var/log/nginx/admin-access.log combined;
    error_log  /var/log/nginx/admin-error.log  warn;

    gzip on; gzip_vary on; gzip_min_length 1000; gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript image/svg+xml;

    location ~* \.(js|css|woff2?|ttf|eot|otf|svg|png|jpg|jpeg|gif|ico|webp|avif)$ {
        try_files $uri =404;
        expires max;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    location = /firebase-messaging-sw.js {
        try_files $uri =404;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Service-Worker-Allowed "/";
    }

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}
