export const DISTRICTS = [
  'COLOMBO', 'GAMPAHA', 'KALUTARA',
  'KANDY', 'MATALE', 'NUWARA_ELIYA',
  'GALLE', 'MATARA', 'HAMBANTOTA',
  'JAFFNA', 'KILINOCHCHI', 'MANNAR', 'MULLAITIVU', 'VAVUNIYA',
  'TRINCOMALEE', 'BATTICALOA', 'AMPARA',
  'KURUNEGALA', 'PUTTALAM',
  'ANURADHAPURA', 'POLONNARUWA',
  'BADULLA', 'MONARAGALA',
  'RATNAPURA', 'KEGALLE',
] as const;

export const PROVINCES = [
  'WESTERN', 'CENTRAL', 'SOUTHERN', 'NORTHERN', 'EASTERN',
  'NORTH_WESTERN', 'NORTH_CENTRAL', 'UVA', 'SABARAGAMUWA',
] as const;

export const OCCUPATIONS = [
  'TEACHER', 'LECTURER', 'PRINCIPAL', 'TUITION_TEACHER', 'SCHOOL_COUNSELOR',
  'TUITION_INSTITUTE_OWNER', 'LIBRARIAN', 'NURSE', 'DOCTOR', 'PHARMACIST',
  'LABORATORY_TECHNICIAN', 'MIDWIFE', 'DENTIST', 'VETERINARY_DOCTOR',
  'PHARMACIST_ASSISTANT', 'MEDICAL_REPRESENTATIVE', 'ENGINEER', 'CIVIL_ENGINEER',
  'ARCHITECT', 'QUANTITY_SURVEYOR', 'SURVEYOR', 'DRAFTSMAN', 'TECHNICIAN',
  'AIR_CONDITIONING_TECHNICIAN', 'AUTO_ELECTRICIAN', 'MOBILE_TECHNICIAN',
  'COMPUTER_TECHNICIAN', 'CCTV_INSTALLER', 'IT_OFFICER', 'SOFTWARE_DEVELOPER',
  'WEB_DEVELOPER', 'GRAPHIC_DESIGNER', 'CONTENT_CREATOR', 'YOUTUBER',
  'DATA_ENTRY_OPERATOR', 'SOCIAL_MEDIA_MARKETER', 'ACCOUNTANT', 'BANK_OFFICER',
  'INSURANCE_AGENT', 'MARKETING_EXECUTIVE', 'ENTREPRENEUR', 'BUSINESS_OWNER',
  'SHOP_OWNER', 'BOUTIQUE_OWNER', 'GROCERY_SHOP_OWNER', 'TAILORING_SHOP_OWNER',
  'BEAUTY_SALON_OWNER', 'BARBER_SHOP_OWNER', 'CONSULTANT', 'MANAGER', 'SUPERVISOR',
  'HR_OFFICER', 'HR_EXECUTIVE', 'PROCUREMENT_OFFICER', 'CLERK', 'CASHIER',
  'RECEPTIONIST', 'CASH_COLLECTOR', 'STORE_KEEPER', 'STORE_MANAGER',
  'WAREHOUSE_ASSISTANT', 'SALES_EXECUTIVE', 'SALESMAN', 'SHOP_ASSISTANT',
  'CALL_CENTER_AGENT', 'CALL_CENTER_SUPERVISOR', 'DRIVER', 'BUS_DRIVER',
  'TUK_TUK_DRIVER', 'TAXI_DRIVER', 'HEAVY_VEHICLE_DRIVER', 'DELIVERY_RIDER',
  'DELIVERY_PARTNER', 'DELIVERY_HELPER', 'DELIVERY_DISPATCHER', 'BUS_CONDUCTOR',
  'DRIVER_ASSISTANT', 'CRANE_OPERATOR', 'FORKLIFT_OPERATOR', 'BUS_OWNER',
  'VEHICLE_INSPECTOR', 'BOATMAN', 'FERRY_OPERATOR', 'FARMER', 'TEA_ESTATE_WORKER',
  'RUBBER_TAPPER', 'COCONUT_FARMER', 'PADDY_FARMER', 'SPICE_CULTIVATOR',
  'VEGETABLE_CULTIVATOR', 'POULTRY_FARMER', 'LIVESTOCK_FARMER', 'DAIRY_FARMER',
  'FISHERMAN', 'FISHER', 'NET_REPAIRER', 'FISH_SELLER', 'POLICE_OFFICER', 'SOLDIER',
  'NAVY', 'AIR_FORCE', 'SECURITY_GUARD', 'SECURITY_SUPERVISOR', 'WATCHMAN',
  'MECHANIC', 'BUS_MECHANIC', 'LIGHT_VEHICLE_MECHANIC', 'ELECTRICIAN', 'PLUMBER',
  'CARPENTER', 'MASON', 'WELDER', 'PAINTER_BUILDING', 'PAINTER_VEHICLE',
  'CONSTRUCTION_WORKER', 'TAILOR', 'DRESSMAKER', 'FASHION_DESIGNER',
  'TAILORING_ASSISTANT', 'HAIRDRESSER', 'BEAUTICIAN', 'BARBER', 'CHEF', 'COOK',
  'BAKER', 'PASTRY_CHEF', 'WAITER', 'WAITRESS', 'HOTEL_STAFF', 'TOUR_GUIDE',
  'ARTIST', 'MUSICIAN', 'DANCER', 'PHOTOGRAPHER', 'VIDEOGRAPHER',
  'PHOTOGRAPHER_ASSISTANT', 'CAMERAMAN', 'ACTOR', 'ACTRESS', 'SINGER',
  'MUSIC_TEACHER', 'PAINTER_ARTIST', 'GYM_INSTRUCTOR', 'SPORTS_COACH',
  'FITNESS_TRAINER', 'HOUSEWIFE', 'HOUSEMAID', 'DOMESTIC_WORKER', 'GARDENER',
  'CLEANER', 'JANITOR', 'FACTORY_WORKER', 'LABOURER', 'FRUIT_SELLER',
  'STREET_VENDOR', 'SMALL_BUSINESS_VENDOR', 'CIVIL_SERVANT', 'GOVERNMENT_OFFICER',
  'GRAMA_NILADHARI', 'POSTMAN', 'LAWYER', 'LEGAL_OFFICER', 'RESEARCHER', 'SCIENTIST',
  'SOCIAL_WORKER', 'NGO_WORKER', 'NGO_FIELD_OFFICER', 'VOLUNTEER_WORKER', 'PRIEST',
  'MONK', 'IMAM', 'RELIGIOUS_LEADER', 'JOURNALIST', 'REPORTER', 'LANDLORD', 'LANDLADY',
  'STUDENT_SCHOOL', 'STUDENT_UNIVERSITY', 'RETIRED_PERSON', 'UNEMPLOYED',
] as const;

export const DISTRICT_TO_PROVINCE: Record<string, string> = {
  COLOMBO: 'WESTERN', GAMPAHA: 'WESTERN', KALUTARA: 'WESTERN',
  KANDY: 'CENTRAL', MATALE: 'CENTRAL', NUWARA_ELIYA: 'CENTRAL',
  GALLE: 'SOUTHERN', MATARA: 'SOUTHERN', HAMBANTOTA: 'SOUTHERN',
  JAFFNA: 'NORTHERN', KILINOCHCHI: 'NORTHERN', MANNAR: 'NORTHERN', MULLAITIVU: 'NORTHERN', VAVUNIYA: 'NORTHERN',
  TRINCOMALEE: 'EASTERN', BATTICALOA: 'EASTERN', AMPARA: 'EASTERN',
  KURUNEGALA: 'NORTH_WESTERN', PUTTALAM: 'NORTH_WESTERN',
  ANURADHAPURA: 'NORTH_CENTRAL', POLONNARUWA: 'NORTH_CENTRAL',
  BADULLA: 'UVA', MONARAGALA: 'UVA',
  RATNAPURA: 'SABARAGAMUWA', KEGALLE: 'SABARAGAMUWA',
};

export function formatEnumLabel(val: string) {
  if (!val) return '';
  return val.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}
