export enum SubscriptionPlan {
  FREE = 'FREE',
  WHATSAPP = 'WHATSAPP',
  TELEGRAM = 'TELEGRAM',
  EMAIL = 'EMAIL',
  PRO_WHATSAPP = 'PRO-WHATSAPP',
  PRO_SMS = 'PRO-SMS',
  PRO_TELEGRAM = 'PRO-TELEGRAM',
  PRO_EMAIL = 'PRO-EMAIL',
  DYNAMAD = 'DYNAMAD'
}
