export enum CalendarDayType {
  REGULAR = 'REGULAR',
  WEEKEND = 'WEEKEND',
  PUBLIC_HOLIDAY = 'PUBLIC_HOLIDAY',
  INSTITUTE_HOLIDAY = 'INSTITUTE_HOLIDAY',
  HALF_DAY = 'HALF_DAY',
  EXAM_DAY = 'EXAM_DAY',
  STAFF_ONLY = 'STAFF_ONLY',
  SPECIAL_EVENT = 'SPECIAL_EVENT',
  CANCELLED = 'CANCELLED',
}

export enum CalendarDaySource {
  AUTO_GENERATED = 'AUTO_GENERATED',
  MANUAL = 'MANUAL',
  BULK_IMPORT = 'BULK_IMPORT',
}

export enum CalendarEventType {
  REGULAR_CLASS = 'REGULAR_CLASS',
  EXAM = 'EXAM',
  PARENTS_MEETING = 'PARENTS_MEETING',
  PRIZE_GIVING = 'PRIZE_GIVING',
  SPORTS_DAY = 'SPORTS_DAY',
  CULTURAL_EVENT = 'CULTURAL_EVENT',
  FIELD_TRIP = 'FIELD_TRIP',
  WORKSHOP = 'WORKSHOP',
  ORIENTATION = 'ORIENTATION',
  OPEN_DAY = 'OPEN_DAY',
  RELIGIOUS_EVENT = 'RELIGIOUS_EVENT',
  EXTRACURRICULAR = 'EXTRACURRICULAR',
  STAFF_MEETING = 'STAFF_MEETING',
  TRAINING = 'TRAINING',
  GRADUATION = 'GRADUATION',
  ADMISSION = 'ADMISSION',
  MAINTENANCE = 'MAINTENANCE',
  CUSTOM = 'CUSTOM',
}

export enum CalendarEventStatus {
  SCHEDULED = 'SCHEDULED',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  POSTPONED = 'POSTPONED',
}

export enum CalendarEventScope {
  INSTITUTE = 'INSTITUTE',
  CLASS = 'CLASS',
  SUBJECT = 'SUBJECT',
}

export enum AttendanceOpenTo {
  TARGET_ONLY = 'TARGET_ONLY',
  ALL_ENROLLED = 'ALL_ENROLLED',
  ANYONE = 'ANYONE',
}

export enum ClassDayType {
  REGULAR = 'REGULAR',
  CLASS_HOLIDAY = 'CLASS_HOLIDAY',
  FIELD_TRIP = 'FIELD_TRIP',
  EXAM_DAY = 'EXAM_DAY',
  EXTRA_CLASS = 'EXTRA_CLASS',
  CANCELLED = 'CANCELLED',
  MERGED = 'MERGED',
  CUSTOM = 'CUSTOM',
}
